name: Cypress Docker Push
on:
  push:
    branches: [ "master" ]

jobs:
  Cypress-Test:


    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: 891376936371.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: pokemon
          IMAGE_TAG: latest
        run: |
          docker build -t pokemon .
          docker build -t pokemon:latest 891376936371.dkr.ecr.ap-south-1.amazonaws.com/pokemon:latest
          docker push 891376936371.dkr.ecr.ap-south-1.amazonaws.com/pokemon:latest
